favicon: null
name: Nature
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.3410311
  brandStrength: 0
  rhythmicContrast: 0.9693877
  brandColors:
    - '#FFFFFF'
    - '#262721'
    - '#A36E5C'
    - '#6F4B3A'
    - '#ABA391'
  lightness: 0.7567132
typography_spectrum: 0.5515575
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9973147
analytics:
  twitter: null
  google: null
  facebook: null
