favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.3410311
  brandStrength: 0
  rhythmicContrast: 0.9693877
  brandColors:
    - '#FFFFFF'
    - '#262721'
    - '#A36E5C'
    - '#6F4B3A'
    - '#ABA391'
  lightness: 0.7567132
typography_spectrum: 0.8050483
layout_spectrum: 0.7749732
analytics:
  twitter: null
  google: null
  facebook: null
name: Nature
